Programme: Start.o Outil.o Placer.o
	gcc -o Programme Start.o Outil.o Placer.o -Wextra -lm

Start.o:Start.c  
	gcc -c Start.c -Wextra -lm

Outil.o:Outil.c 
	gcc -c Outil.c -Wextra -lm

Placer.o:Placer.c
	gcc -c Placer.c -Wextra -lm
